import { Inter,Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider} from "@clerk/nextjs";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Magna-AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  return (
    <ClerkProvider>
    <html lang="en">
        <meta name="google-site-verification" content="paPIDxqrB5gmTSLUoEBQaWwIIp2yhI-i6gCNbIVig4s" />
      <body className={inter.className}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
